### ISSUE TITLE
v2.0.0rc1 on pip doesn't contain the necessary files.

### ISSUE THREAD

**Issue by UpstreamData** [exhuma/puresnmp#101]
I installed puresnmp 2.0.0rc1 off of pip, and when running this code (essentially straight out of the [docs](https://puresnmp.readthedocs.io/en/develop/upgrading.html) with asyncio.run()):
```
from puresnmp import Client, ObjectIdentifier, V2C
import asyncio


client = Client("192.0.2.1", V2C("private"))
result = asyncio.run(client.get(ObjectIdentifier("1.3.6.1.2.1.1.2.0")))
print(repr(result))
```

I get an ModuleNotFoundError for PyWrapper.
```
    from puresnmp.api.pythonic import PyWrapper
ModuleNotFoundError: No module named 'puresnmp.api'
```

Directory structure of venv/Lib/puresnmp:
```
adt.py
const.py
credentials.py
exc.py
pdu.py
py.typed
transport.py
types.py
typevars.py
util.py
varbind.py
__init__.py
```

It appears that `puresnmp.api` doesn't exist at all.

From there, I tried going back to a previous version (which still displays as latest for some reason...), and looked through it again.  `/api/__init__.py` exists in 1.11.0, but the file is empty, meaning even if I somehow had both installed it wouldn't import.

_Originally posted by @UpstreamData in https://github.com/exhuma/puresnmp/issues/100#issuecomment-1133012907_

**Comment by UpstreamData** [comment]
Solution suggested here, attempting to migrate this thread off of the original PR into this issue.

@GhostofGoes

https://github.com/exhuma/puresnmp/pull/100#issuecomment-1133096014

**Comment by UpstreamData** [comment]
> That's weird... I will look into this.

Also, `typing_extensions` doesn't install when pip installing puresnmp, that may need to be added as well (although I know nothing about pip installations or PyPi)

**Comment by exhuma** [comment]
It's fine. I do have quite some experience with this and will figure it out. It is definitely not properly picking up the package files when building the dist. I'm looking into it as we speak :)

**Comment by exhuma** [comment]
Pipeline is triggered: https://github.com/exhuma/puresnmp/actions/runs/2359564353

Once that is through, v2.0.0rc2 should appear on pypi momentarily. The package looks more correct now. Hope I didn't miss anything... fingers crossed...

**Comment by exhuma** [comment]
I missed the issue with the incorrect initialisation of the protocol class. This was introduced with Python 3.8 support yesterday. At work we're still on 3.6 so that did not surface yet.

I'm confident that these are just minor kinks to be ironed out with the changes I had to do for Python 3.8+.

2.0.0rc3 should be available soon with that fix.

Let me know if it's fixed or not.

**Comment by UpstreamData** [comment]
> I missed the issue with the incorrect initialisation of the protocol class. This was introduced with Python 3.8 support yesterday. At work we're still on 3.6 so that did not surface yet.
> 
> I'm confident that these are just minor kinks to be ironed out with the changes I had to do for Python 3.8+.
> 
> 2.0.0rc3 should be available soon with that fix.
> 
> Let me know if it's fixed or not.

It fixed the original issue, but now `plugins/mpm.py` is raising a new issue.

```
    raise UnknownMessageProcessingModel(
puresnmp.exc.UnknownMessageProcessingModel: Namespace 'puresnmp_plugins.mpm' did not contain a plugin with identifier 1. 
Known identifiers: []. 
See the 'puresnmp' documentation on plugins.
```

I can't find anything in a quick search of the docs about plugins and I don't think it should raise this on initial install?

**Comment by UpstreamData** [comment]
> I missed the issue with the incorrect initialisation of the protocol class. This was introduced with Python 3.8 support yesterday. At work we're still on 3.6 so that did not surface yet.

FYI I am on python 3.10 right now, so I will likely have a LOT more issues than you, I will try to give as much info as possible on what I do encounter, but I could see this being troublesome.

**Comment by exhuma** [comment]
oh ffs... I'm really sorry about this. I'm currently not at the office and have neither a proper dev-setup here for real in-depth testing, nor access to a network device for testing. So it's a bit of a whack-a-mole at the moment until all of this is through.

Please bear with me 😅

**Comment by exhuma** [comment]
This does all look like a packaging issue though. I will see if I can repro this in the automated pipeline tests... this would definitely help.

**Comment by UpstreamData** [comment]
No stress @exhuma, it's not a major rush at all for me, long weekend coming up and I will likely not get anything done on this until Tuesday, and if all else fails I can guess pretty well about how I want to implement it, so I can always work on that.

**Comment by exhuma** [comment]
Thanks for the patience :)

**Comment by exhuma** [comment]
rc5 is released. Manually downloading and inspecting the contents looks fine now.

**Comment by GhostofGoes** [comment]
Yup, `rc5` seems to have resolved both the `ModuleNotFoundError` and `UnknownMessageProcessingModel` errors for me (Python 3.8). Thanks for the rapid fixes 😸

**Comment by UpstreamData** [comment]
Yep, seems to work now for me.  Appreciated.
