### ISSUE TITLE
when v2.x can install from pip

### ISSUE THREAD

**Issue by beruhan** [exhuma/puresnmp#103]
hello,when v2.x can install from pip

**Comment by exhuma** [comment]
Indeed the pre-releases are working. I did not get around to flag them as full release yet. But for all intents and purposes they can be considered as such. I will flag them as soon as I get around to it.

If you need to define them as dependency in a `pyproject.toml` or `setup.py`, you should be able to do something like this:

`puresnmp>=2.0.0rc6, <3.0`

which *should* work (I have no Python around on this machine and could not veryify it). The above spelling should allow "rc6" to be installed, and auto upgrade if a new release comes out.... I think...

Considering that they are already installable I will close this issue.

**Comment by exhuma** [comment]
I just verified my post above to be working.
