### ISSUE TITLE
ERROR: No matching distribution found for pack==1.1,==1.3; extra == "rest"

### ISSUE THREAD

**Issue by frogmaster** [exhuma/puresnmp#105]
## Issue Description

Not installable package "pack" in optional.extras_require in setup.cfg.

```
$ pip install "puresnmp[rest]==2.0.0" --upgrade  
Collecting puresnmp[rest]==2.0.0
  Using cached puresnmp-2.0.0-py3-none-any.whl (61 kB)
Collecting x690<2.0,>=1.0
  Using cached x690-1.0.0-py3-none-any.whl (29 kB)
ERROR: Could not find a version that satisfies the requirement pack==1.1,==1.3; extra == "rest" (from puresnmp[rest]) (from versions: none)
ERROR: No matching distribution found for pack==1.1,==1.3; extra == "rest"

```
Although this is not a major problem when using pip and not installing the extra, it makes using poetry 1.2.1 impossible. Poetry writes 'rest = ["docutils (>=0.3)", "pack (< empty >)"]' into poetry.lock, even when not trying to install the extra, and after that lock file parsing fails (poetry version 1.2.1).

**Comment by exhuma** [comment]
Thanks for reporting this. This is an error in the `setup.cfg` file. The extras `pdf` and `rest` were old "bugfixes" for "readthedocs" and are no longer required. I removed those extras to avoid this issue.

For your particular case, you can simply remove the `[rest]` extra in your installation. It will not have any effect on the code itself.

**Comment by frogmaster** [comment]
Thanks for the quick fix, by the way, x690 has the same issue.

**Comment by exhuma** [comment]
Thanks again for reporting. I've just pushed a new `x690` release with the same fix.
