### ISSUE TITLE
mportError: cannot import name 'get' from 'puresnmp

### ISSUE THREAD

**Issue by frsoto** [exhuma/puresnmp#113]
Hi, can anyone help me with this please?

root@prov:/home/operador# pip install puresnmp   
Collecting puresnmp
  Downloading puresnmp-2.0.0.post1-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 603 kB/s 
Collecting x690<2.0,>=1.0
  Downloading x690-1.0.0.post1-py3-none-any.whl (29 kB)
Collecting t61codec<2.0,>=1.0.1
  Downloading t61codec-1.0.1-py2.py3-none-any.whl (6.0 kB)
Installing collected packages: t61codec, x690, puresnmp
Successfully installed puresnmp-2.0.0.post1 t61codec-1.0.1 x690-1.0.0.post1
root@prov:/home/operador# 
root@prov:/home/operador# 
root@prov:/home/operador# python3
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from puresnmp import  get
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ImportError: cannot import name 'get' from 'puresnmp' (/usr/local/lib/python3.8/dist-packages/puresnmp/__init__.py)**
>>> quit()

**Comment by exhuma** [comment]
In puresnmp 2.x, the API changed. Please see [the upgrade guide](https://puresnmp.readthedocs.io/en/latest/upgrading.html) and/or [the full documentation](https://puresnmp.readthedocs.io/en/latest/)

**Comment by exhuma** [comment]
As there was no further feedback, I assume that this is working and consider this closed.

**Comment by frsoto** [comment]
> [xhuma](/exhuma)

sorry exhuma... i was in trouble.
thank you very much
