### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by h5rdly** [exhuma/puresnmp#116]
Hi,

First of all, cheers for this sweet project, seems like the best python option for snmpv2!

I tried to get to the documentation, it seems to be down - 
https://puresnmp.readthedocs.io/en/latest/cookbook/index.html

Would it be possible to fix it, or supply it in some other way? perhaps inside github?

Thanks,
Eli

**Comment by exhuma** [comment]
Ah... seems to be a dead link in the Readme file. If you drop the path from the URL it works: https://puresnmp.readthedocs.io/en/latest/

**Comment by h5rdly** [comment]
Thanks for the fix!

I see in the changelog  - 
https://puresnmp.readthedocs.io/en/latest/changelog.html#release-2-0-0post1-maintenance-release

that `puresnmp` now supports v3 as well. Worth mentioning in the readme :)

(A pure Python implementation for Python 3.6+ of SNMP V1/2/3 without... )
