### ISSUE TITLE
pyinstaller packaging

### ISSUE THREAD

**Issue by remdragon** [exhuma/puresnmp#34]
Ran into an issue when packaging up puresnmp in a project with pyinstaller.

The program wouldn't run because version.txt didn't get included.

Can I remove dependency on that file or prevent the script from crashing if it can't be found?

**Comment by exhuma** [comment]
I have no experience with pyinstaller.

Having a `version.txt` in the project makes it easy to change version numbers as you have only one single location to modify and makes it very easy to read with other external tools during development. If there is no way to fix the pyinstaller packaging *without* internalising the version number then I don't see an issue with internalising.

If you can, investigate the exact issue with `pyinstaller`. It sounds to me like it's ignoring `MANIFEST.in` and/or the `include_package_data` flag from `setup.py`.

I would be surprised if `pyinstaller` would have problems with "package data" as it is a standard feature for Python packages.

**Comment by flazzarini** [comment]
I recently ran into similar issues with `pyinstaller`. It really seems that `pyinstaller` is not respecting the `MANIFEST.in` file. As a workaround you can use the `--add-data` option. Like so

`pyinstaller --noconsole --add-data "project_name/version.txt" startup.py`

Quick question though. Are you using `puresnmp` in another package of yours for which you would like to compile an Windows executable file?

**Comment by exhuma** [comment]
Given that this is not really an issue with `puresnmp`  I will close this.

Thanks @flazzarini for pointing out the solution.

**Comment by exhuma** [comment]
Needs to be reviewed.

**Comment by exhuma** [comment]
@remdragon I've moved the version info into a python file instead of a text file. Can you try if this works better with pyinstaller?

**Comment by remdragon** [comment]
when I pip install from python3 I'm getting version 1.2.1, but when I pip
install from python 2 I'm getting version 1.1.5. Both versions still appear
to have the version.txt file



Royce Mitchell, IT Consultant
ITAS Solutions
royce3@itas-solutions.com

**Comment by exhuma** [comment]
Oh, I realised I forgot to upload the latest release-candidate from today to pypi. But in any case, the new release is currently flagged as "prerelease" (using the `rc<n>` suffix) which `pip` ignores by default. I want to keep it as RC until you give me green light to flag it as final. You can also see this [on the pypi history page](https://pypi.org/project/puresnmp/#history)

To allow `pip` to include the pre-release, you can add the `--pre` flag.

Or use the following as dependency:  `puresnmp >= 1.3.0rc3`
