### ISSUE TITLE
Can't find OID in aio.api.pythonic.set()

### ISSUE THREAD

**Issue by acspike** [exhuma/puresnmp#61]
I get an exception on ```set()``` at [line 137](https://github.com/exhuma/puresnmp/blob/develop/puresnmp/aio/api/pythonic.py#L137) if I supply an oid with an initial dot. The result returns oids with the initial dot stripped. Some canonicalization of the input OID is needed. Perhaps it could be as simple as ```oid.lstrip('.')```?

**Comment by exhuma** [comment]
Yes. The `lstrip` will suffice.

One early design decision of the library was to consider *all* OIDs as absolute OIDs. Relative OIDs are rarely used. So the leading dot became redundant.

This may not have been the smartest decision but that's how it is for now.

Stripping the leading dot from the input will remove the exception.

**Comment by acspike** [comment]
Does this need to get done in both aio and sync then?

**Comment by exhuma** [comment]
Yes. I should be able to get this fixed today.

**Comment by exhuma** [comment]
I believe that the decision to strip the leading dot was in general a mistake. I will apply a patch which fixes this immediate issue by using `lstrip` as you mention. But after that I'll try if I can remove that "dot-stripping" behaviour throughout all of the code-base without breaking backwards-compatibility.

If that's possible I'll remove it (making the `lstrip` redundant again).

The `lstrip` will be  quick-fix in the mean-time.

**Comment by exhuma** [comment]
Fixe in 1.5.2
