### ISSUE TITLE
Counter32 is treated as a signed int

### ISSUE THREAD

**Issue by scotloach** [exhuma/puresnmp#63]
puresnmp 1.6.1 on python 3.7.3

Counter32 types return a signed integer.  It should returned an unsigned integer.
i.e. for values > 2^31, negative numbers are returned.

**Comment by exhuma** [comment]
Thanks for reporting this. I'll have a look.

**Comment by exhuma** [comment]
Should be fixed in [Release 1.6.2](https://pypi.org/project/puresnmp/#history)
