### ISSUE TITLE
unexpected value for OctetString type

### ISSUE THREAD

**Issue by hyzeer** [exhuma/puresnmp#64]
Hi,  thank you for the project, it's great.
but I had a problem:
a OID, it will return a chars of length 12,  such as `ZTEGC553F9C0`. in wireshark, the value is the following:

![image](https://user-images.githubusercontent.com/29218168/62831921-0bf18680-bc59-11e9-956e-07fd302d63eb.png)

but in puresnmp, the value is `b'ZTEG\xc5S\xf9\xc0'`. 
How should I decode `b'\xc5S\xf9\xc0'`?

**Comment by hyzeer** [comment]
I got it, thanks.

**Comment by exhuma** [comment]
Glad you managed to work it out. And I am glad you like the library :)

To give you a bit more context:

The encoding for this value is probably defined in a MIB. It might me prudent to look that up. Given that this is in the vendor tree (`1.3.6.1.4.1...`) the definition should be in a MIB provided by the vendor.

One of the aim of `puresnmp` is to be agnostic about MIBs. Even the standard MIB-2 as they caused problems in a project I am working on. When not using MIBs the concept of a "Display String" (or any other specialisation of `OctetString`) is missing. So all you have is `OctetString` and those are returned as bytes in `puresnmp` as it is impossible to reliably guess the encoding. 

In your case, if you want to see the hex-value, all you have to do is call [`.hex()`](https://docs.python.org/3/library/stdtypes.html#bytes.hex) on the bytes object.

**Comment by hyzeer** [comment]
thanks for your reply.

I agree with the design concept of puresnmp. :)

as you mentioned, I used` .hex()` on the bytes object. This is my blind spot of knowledge.😥
