### ISSUE TITLE
Import error: bulktable is missing from init

### ISSUE THREAD

**Issue by 2mmi** [exhuma/puresnmp#73]
Hi 

I just ran into this problem.

Traceback (most recent call last):
  File "Z:\libexec\tomitest.py", line 5, in <module>
    from puresnmp import bulktable
ImportError: cannot import name 'bulktable' from 'puresnmp' (C:\Python37\lib\site-packages\puresnmp\__init__.py)
[Finished in 0.2s with exit code 1]

 - Thanks for nice/clean package !

Best regards Tommi

**Comment by exhuma** [comment]
Thanks for reporting this. That's an easy fix and will deal with it in the coming days.

And thanks for the compliment 😄

**Comment by exhuma** [comment]
Has been released as `v1.7.3`
